- hosts: all
  tags: prereqs
  roles:
    - { role: validation_prereq }

- hosts: all
  serial: 1
  roles:
    - { role: validation }

- hosts: all
  tasks:
    - name: kill off rpctest servers
      command: pkill -f rpctest

